readaloud/book/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.book_index, name="book_index"),
    path("<slug>/", views.book_detail, name="book_detail"),
]

readaloud/readaloud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from fbv.views import html_view
from markdownx import urls as markdownx


urlpatterns = [
    path("admin/", admin.site.urls),
    path("book/", include("book.urls")),
    path("", html_view, {"template_name": "front.html"}),
    path("markdownx/", include(markdownx)),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

readaloud/book/models.py
from django.db import models
from django.urls import reverse

from tagulous.models import TagField
from markdownx.models import MarkdownxField


class Author(models.Model):
    name = models.CharField(max_length=144)

    def __str__(self):
        return str(self.name)


class VisibleBookManager(models.Manager):
    def all_visible(self):
        return self.filter(display=True)


class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    illustrator = models.ForeignKey(
        Author,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name="illustrator_set",
    )
    name = models.CharField(max_length=144)
    slug = models.SlugField(null=False)  # TODO: Needs to be unique
    categories = TagField(blank=True)
    description = MarkdownxField(help_text="Use markdown for formatting")
    year = models.IntegerField()
    age = models.IntegerField(
        blank=True, null=True, help_text="Add an appropriate age for this book."
    )
    goodreads = models.URLField(
        help_text="Add link to goodreads page", blank=True, null=True
    )
    display = models.BooleanField(
        default=True, help_text="Uncheck to hide on the site."
    )
    cover = models.ImageField(blank=True, null=True, upload_to="books/covers/")

    objects = VisibleBookManager()

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"slug": self.slug})


class Series(models.Model):
    title = models.CharField(max_length=144)
    book = models.ManyToManyField(Book)


    class Meta:
        verbose_name_plural = "Series"


    def __str__(self):
        return self.title

readaloud/book/views.py
from django.shortcuts import get_object_or_404

from book.models import Book

from fbv.decorators import render_html


@render_html()
def book_index(request):
    categories = Book.categories.tag_model
    return {
        "books": Book.objects.all_visible(),
        "page": "book",
        "tags": categories.objects.all(),
    }


@render_html()
def book_detail(request, slug):
    return {"book": get_object_or_404(Book, slug=slug, display=True), "page": "book"}

readaloud/book/templates/book/book_base.html
{% extends "base.html" %}

{% block main %}

 {% block book_content %}
 {% endblock %}

{% endblock %}

readaloud/book/templates/book/book_detail.html
{% extends "book/book_base.html" %}

{% block title %}{{ book }}{% endblock %}

{% block book_content %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="..">Books</a></li>
    <li class="is-active"><a href="#">{{ book }}</a></li>
  </ul>
</nav>

<hr/>

<h1 class="title is-1">{{ book }}</h1>
{% if book.categories.all %}
<div class="block">
  {% for tag in book.categories.all %} <span class="tag is-link is-light">{{ tag }}</span> {% endfor %}
</div>
{% endif %}
{% if book.series_set.all %}
  <div class="block is-size-7">
  {% with book.series_set.all.first as series %}
    <span class="tag is-info is-rounded" style="float:right">Series!</span>
    <p>{{ series }}:
    {% for sub_book in series.book.all %}
      {% if sub_book != book %}
          <a href="{{ sub_book.get_absolute_url }}">{{ sub_book }}</a> {% if not forloop.last %}/{% endif %}
      {% endif %}
    {% endfor %}
    </p>

  {% endwith %}
  </div>
{% endif %}


{% if book.cover %}
  <figure class="is-pulled-left cover-detail">
  <img class="" src="{{ book.cover.url }}" alt="Cover Photo" width="256">
  </figure>
{% endif %}

{% load markdowny_tags %}
{{ book.description|markdowny }}

{% if book.age %}
<p>Ages: {{ book.age }}+<p>
{% endif %}

{% if book.goodreads %}
<p><a target="_new" href="{{ book.goodreads }}">Goodreads Link</a><p>
{% endif %}

{% endblock %}

readaloud/book/templates/book/book_index.html
{% extends "book/book_base.html" %}

{% block title %}
Book List
{% endblock %}

{% block book_content %}
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li class="is-active"><a href="#">Books</a></li>
  </ul>
</nav>

<hr />
<h1 class="title is-1">Books</h1>
<div class="block">
  Categories: {% for tag in tags %} <span class="tag is-link is-light">{{ tag }}</span> {% endfor %}
</div>
<div class="tile is-ancestor" style="flex-wrap: wrap;">
  {% for book in books %}
    <div class="tile is-parent is-3">
    <div class="tile is-child">
    {% include "book/card.html" %}
    </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

readaloud/book/templates/book/card.html
<div class="card">
  <div class="card-image">
    <figure class="image">
      {% if book.cover %}
      <img class="" src="{{ book.cover.url }}" alt="Cover Photo">
      {% else %}
      <img src="https://bulma.io/images/placeholders/128x128.png" alt="Placeholder image">
      {% endif %}
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4"><a href="{{ book.get_absolute_url }}">{{ book }}</a></p>
        <p class="subtitle is-6">by {{ book.author }}</p>
      </div>
    </div>
    <div class="content">
      {% if book.age %}
      Age: {{ book.age }}+
      {% endif %}
      {% for tag in book.categories.names %}
        {% if forloop.first %}<p>{% endif %}
        <span class="tag is-info">{{tag }}</span>
        {% if forloop.last %}</p>{% endif %}
      {% endfor %}
    </div>
  </div>
</div>

readaloud/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Readaloud - {% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  {% load static %}
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Nunito&display=swap');
  	body {font-family: 'Nunito', sans-serif;};
    nav.navbar {
      height: 6rem !important;
      box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06) !important;
    }
  </style>
</head>

<body>
  <!-- START NAV -->
  <nav class="navbar">
    <div class="container">
      <div class="navbar-brand">
        <span class="navbar-burger burger" data-target="navbarMenu">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </div>
      <div id="navbarMenu" class="navbar-menu">
        <div class="navbar-end">
          <div class=" navbar-item">
            <div class="control has-icons-left">
              <input class="input is-rounded" type="email" placeholder="Search">
              <span class="icon is-left">
                <i class="fa fa-search"></i>
              </span>
            </div>
          </div>
          <a class="navbar-item {% if page is None %}is-active{% endif %} is-size-5 has-text-weight-semibold" href="/">
            Home
          </a>
          <a class="navbar-item is-size-5 has-text-weight-semibold {% if page == 'book' %}is-active{% endif %}" href="/book/">
            Books
          </a>
        </div>
      </div>
    </div>
  </nav>
  <!-- END NAV -->
  <section class="section">
    <div class="columns">
      <div class="column is-10 is-offset-1">
        {% block main %}
        {% endblock %}
      </div>
    </div>
  </section>

  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Footer</strong>
      </p>
    </div>
  </footer>

  <script>
    document.addEventListener('DOMContentLoaded', () => {

      // Get all "navbar-burger" elements
      const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

      // Check if there are any navbar burgers
      if ($navbarBurgers.length > 0) {

        // Add a click event on each of them
        $navbarBurgers.forEach(el => {
          el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

          });
        });
      }

    });
  </script>
   {% if debug %}
     <script type="text/javascript" src="/static/js/live.js" async="async"></script>
   {% endif %}
</body>

</html>

readaloud/templates/front.html
{% extends "base.html" %}

{% block title %} Read with your whole family{% endblock %}

{% block main %}
<p>test</p>
{% endblock %}